2024-11-10 11:11:25,224 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\pythonProjectsForUniversity\lessons\lesson_12\tests_12_4.py", line 23, in test_run
    r = rt.Runner(2)
        ^^^^^^^^^^^^
  File "D:\pythonProjectsForUniversity\lessons\lesson_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-10 11:11:25,244 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\pythonProjectsForUniversity\lessons\lesson_12\tests_12_4.py", line 12, in test_walk
    r = rt.Runner('Вася', -5)
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProjectsForUniversity\lessons\lesson_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
